### ISSUE TITLE
Preview loads item twice on page load of item overview page

### ISSUE THREAD

**Issue by philipkueng** [nzzdev/Q-editor#235] opened 2019-09-19 07:46 UTC
In this [particular item](https://q.st.nzz.ch/item/ee9d06343c078de3d26488bda0a0d0bc), the preview loads the item twice. Not sure why though.

**Comment by romankaravia** [comment] 2020-04-17 10:56
Reproduced [here](https://q.st-staging.nzz.ch/item/6dcf203a5c5f74b61aeea0cb0eef8942).

The init script is run twice when loading the Q-Editor page:
![image](https://user-images.githubusercontent.com/47303530/79561677-66799700-80b2-11ea-9cd4-9e0dbf1700a5.png)

But when the preview is reloaded later, e.g. if you switch to "Content" afterwards, the init script runs only once:
![image](https://user-images.githubusercontent.com/47303530/79561870-bc4e3f00-80b2-11ea-993b-9e15a6c14fb4.png)

The problem can only be reproduced with some asynchronous code in the init script, because (it looks like) the DOM element is cleared between the two runs of the init script.

**Comment by romankaravia** [comment] 2020-04-29 08:00
Fixed in v6.2.5

**Closed by romankaravia** 2020-04-29 08:00 UTC
